name: Run test, lint, build app, build storybook
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main]
jobs:
  pipline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v2

      - name: install NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dep
        run: npm install

      - name: start esLint
        run: npm run lint:ts

      - name: run tests
        run: npm run unit

      - name: build app if test was success
        if: success()
        run: npm run build:prod



